AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for simple-nodejs-backend application'

Parameters:
  ProjectPrefix:
    Type: String
    Description: The name of the VPC stack to get outputs from
    Default: stepan
    
  ImageTagMutability:
    Type: String
    Default: MUTABLE
    AllowedValues:
      - MUTABLE
      - IMMUTABLE
    Description: The tag mutability setting for the repository
    
  ScanOnPush:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable image scanning on push

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectPrefix}-ecr-repository"
      ImageTagMutability: !Ref ImageTagMutability
      ImageScanningConfiguration:
        ScanOnPush: !Ref ScanOnPush
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the latest 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryURI:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"
      
  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref ECRRepository
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryName"
